#!/bin/bash


# COPIED FROM https://github.com/eitsupi/rocker-versioned2/blob/master/scripts/install_tidyverse.sh
# removed duckdb and arrow due to compilation errors
# added several other packages

set -ex

BUCKET=$1

NCPUS=`nproc --all`

echo building using $NCPUS cpu count

# a function to install apt packages only if they are not installed
function apt_install() {
    if ! dpkg -s "$@" >/dev/null 2>&1; then
        if [ "$(find /var/lib/apt/lists/* | wc -l)" = "0" ]; then
            apt-get update
        fi
        apt-get install -y --no-install-recommends "$@"
    fi
}

apt-get install -y gnupg

apt-key adv --keyserver keyserver.ubuntu.com --recv-key '95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7'
echo "deb http://cloud.r-project.org/bin/linux/debian bullseye-cran40/" > /etc/apt/sources.list.d/r.list
apt-get update
apt-get install -y \
    libatlas3-base \
    r-base \
    r-base-dev \
    gdebi-core

apt-get -y upgrade

wget --no-verbose -O /tmp/rstudio.deb  https://download2.rstudio.org/server/bionic/amd64/rstudio-server-2022.12.0-353-amd64.deb
gdebi -n /tmp/rstudio.deb

cat << EOF > /etc/rstudio/rserver.conf
www-frame-origin=any
www-port=80
EOF


apt_install \
    ca-certificates \
    lsb-release \
    file \
    libapparmor1 \
    libclang-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libobjc4 \
    libssl-dev \
    libpq5 \
    psmisc \
    procps \
    python-setuptools \
    pwgen \
    libxml2-dev \
    libcairo2-dev \
    libgit2-dev \
    default-libmysqlclient-dev \
    libpq-dev \
    libsasl2-dev \
    libsqlite3-dev \
    libssh2-1-dev \
    libxtst6 \
    libcurl4-openssl-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    unixodbc-dev \
    libgdal-dev \
    r-cran-docopt \
    r-cran-littler

ln -s /usr/lib/R/site-library/littler/examples/install2.r /usr/local/bin/install2.r

install2.r --error --skipinstalled -n "$NCPUS" \
    tidyverse \
    devtools \
    rmarkdown \
    BiocManager \
    vroom \
    gert \
    jsonlite \
    rvest \
    qualtRics \
    kableExtra \
    shiny \
    leaflet \
    plotly \
    psych \
    careless \
    RSQLite \
    devtools

# dbplyr \
#     DBI \
#     dtplyr \
#     devtools \
#     nycflights13 \
#     Lahman \
#     RSQLite \
#     fst

## a bridge to far? -- brings in another 60 packages
# install2.r --error --skipinstalled -n "$NCPUS" tidymodels

# Clean up
## Strip binary installed lybraries from RSPM
## https://github.com/rocker-org/rocker-versioned2/issues/340
strip /usr/local/lib/R/site-library/*/libs/*.so

# Check the tidyverse core packages' version
echo -e "Check the tidyverse package...\n"
R -q -e "library(tidyverse)"
echo -e "\nInstall tidyverse package, done!"

cd /tmp
aws s3 cp s3://$BUCKET/configs/kinetic-r-api.tar.gz ./
tar zxf kinetic-r-api.tar.gz
sudo R -e "devtools::install('kinetic')"

echo -e "\nInstall kinetic package, done!"
