#!/bin/bash

DOMAIN=$1
KEY=$2

echo domain is $DOMAIN

wget --no-verbose -O /tmp/rstudio.deb  https://download2.rstudio.org/server/bionic/amd64/rstudio-server-2023.03.1-446-amd64.deb

gdebi -n /tmp/rstudio.deb

cat << EOF > /etc/rstudio/rserver.conf
www-frame-origin=any
www-port=80
EOF

perl -p -i -e "s|</head>|<script src=\"https://$DOMAIN/assets/kinetic-rstudio-editor-patch.js\"></script>\n</head>|" /usr/lib/rstudio-server/www/index.htm

echo $KEY > /var/lib/rstudio-server/secure-cookie-key
